server:
  port: 9002

spring:
  application:
    name: query-product
  cloud:
    nacos:
      discovery:
        server-addr: localhost:6448
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3308/db_product
    username: root
    password: 123456
  servlet:
    multipart:
      max-file-size: 1MB

# 文件保存路径：应当为nginx对应静态资源路径
file-path: D:\coding\sale-mall\mall-dependencies-docker-compose\nginx-server\www\upload\
# 图片保存头，为对应file-path中www下的路径
pic-pref: /upload/

management:
  endpoints:
    web:
      exposure:
        include: '*'
mybatis-plus:
  configuration:
    # 开启驼峰命名转换
    map-underscore-to-camel-case: true