version: "3"
services:
  # nacos-server服务注册与发现，配置中心服务    
  mall-nacos2:
    image: nacos/nacos-server:${NACOS_VERSION}
    container_name: mall-nacos2
    ports:
      - "8849:8848"
      - "9849:9848"
    env_file:
      - ./env/nacos-hostname.env
    networks: 
      mall_net:
        ipv4_address: 172.18.0.4
    restart: on-failure
    privileged: true
    volumes:
      - ./cluster-logs/nacos2:/home/nacos/logs #日志输出目录
      - ./init.d/custom.properties:/home/nacos/init.d/custom.properties #../init.d/custom.properties内包含很多自定义配置，可按需配置

networks:
  mall_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16