version: "3" 
services:
  # nacos-server服务注册与发现，配置中心服务    
  mall-nacos1:
    image: nacos/nacos-server:${NACOS_VERSION}
    container_name: mall-nacos1
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9555:9555"
      # - "9849:9849"
    env_file:
      - ./env/nacos-hostname.env
    networks: 
      mall_net:
        ipv4_address: 172.18.0.3
    restart: on-failure
    privileged: true
    volumes:
      - ./cluster-logs/nacos1:/home/nacos/logs #日志输出目录
      - ./init.d/custom.properties:/home/nacos/init.d/custom.properties #../init.d/custom.properties内包含很多自定义配置，可按需配置

networks:
  mall_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16