version: "3"
services:
  mysql-mall:
      container_name: mysql-mall
      image: nacos/nacos-mysql:5.7
      environment:
        - MYSQL_ROOT_PASSWORD=123456
      ports:
        - "3308:3306"
      networks: 
        mall_net:
          ipv4_address: 172.18.0.9
      restart: on-failure
      volumes:
        - ./mysql-conf/mysql.conf.d/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
        - ./mysql-mall-databases:/var/lib/mysql

networks:
  mall_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16