version: "3" 
services:
  mall-nginx-server:
    image: nginx
    container_name: mall-nginx-server
    ports:
      - "8080:8080"
      - "8081:8081"
    restart: on-failure
    networks: 
      mall_net:
        ipv4_address: 172.18.0.10
    volumes:
      - ./nginx-server/www:/usr/share/nginx/html
      - ./nginx-server/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx-server/logs:/var/log/nginx

networks:
  mall_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16