server:
  port: 9001

spring:
  application:
    name: query-user
  cloud:
    nacos:
      discovery:
        server-addr: localhost:6448
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3308/db_user
    username: root
    password: 123456

management:
  endpoints:
    web:
      exposure:
        include: '*'
mybatis-plus:
  configuration:
    # 开启驼峰命名转换
    map-underscore-to-camel-case: true