server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:6448
    gateway:
      discovery:
        locator:
          enabled: true   #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: seckill_router
          uri: lb://query-seckill
#          uri: http://localhost:9004
          predicates:
            - Path=/seckill/**
        - id: product_router
          uri: lb://query-product
          predicates:
            - Path=/product/**
        - id: user_router
          uri: lb://query-user
          predicates:
            - Path=/user/**
        - id: order_router
          uri: lb://query-order
          predicates:
            - Path=/order/**
        - id: create_rouoter
          uri: lb://seckill-restrictor
          predicates:
            - Path=/create/**
#        - id: payment_routh #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          #          uri: http://localhost:8001          #匹配后提供服务的路由地址
#          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
#          predicates:
#            - Path=/payment/get/**         # 断言，路径相匹配的进行路由
#            - Method=GET
#        #            - After=2021-11-22T10:30:35.386057700+08:00[GMT+08:00]
#
#        - id: payment_routh2 #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          #          uri: http://localhost:8001          #匹配后提供服务的路由地址
#          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
#          predicates:
#            - Path=/payment/lb/**         # 断言，路径相匹配的进行路由
#            - Method=GET
#    #            - Cookie=username,zzyy
    ####################################################################